  apiVersion: v1
  kind: Service
  metadata:
    name: Checkpoint OrchestrationServices
  spec:
    type: NodePort
    selector:
      app: fontend
    ports:
    - port: 40
      targetPort: 30000
  